gfx_background: @(fetch-file "obj/gfx-background.bin.exo")

bg_brick_orange  = @(+ bg_start 0)
bg_brick         = @(+ bg_start 1)
bg_brick_special = @(+ bg_start 2)
bg_side          = @(+ bg_start 3)
bg_side0         = @(+ bg_start 3)
bg_side1         = @(+ bg_start 4)
bg_side2         = @(+ bg_start 5)
bg_side3         = @(+ bg_start 6)
bg_side4         = @(+ bg_start 7)
bg_corner_left   = @(+ bg_start 8)
bg_top0         = @(+ bg_start 9)
bg_top1         = @(+ bg_start 10)
bg_top2         = @(+ bg_start 11)
bg_corner_right  = @(+ bg_start 12)
bg_break         = @(+ bg_start 13)
bg_minivaus      = @(+ bg_start 15)
bg_brick_fx      = @(+ bg_start 16)
bg_brick_fx_end  = @(+ bg_start 23)

bg_gate0         = @(+ bg_start 24)
bg_gate1         = @(+ bg_start 25)
bg_gate2         = @(+ bg_start 26)
bg_gate3         = @(+ bg_start 27)
bg_gate4         = @(+ bg_start 28)
bg_gate5         = @(+ bg_start 29)

bg_animated_gate0 = 126
bg_animated_gate1 = 127
