gfx_background: @(fetch-file "obj/gfx-background.bin.exo")

bg_brick_orange = @(+ bg_start 0)
bg_brick = @(+ bg_start 1)
bg_brick_special = @(+ bg_start 2)
bg_side = @(+ bg_start 3)
bg_corner_left = @(+ bg_start 8)
bg_top_1 = @(+ bg_start 9)
bg_top_2 = @(+ bg_start 10)
bg_top_3 = @(+ bg_start 11)
bg_corner_right = @(+ bg_start 12)
bg_break = @(+ bg_start 13)
bg_star = @(+ bg_start 15)
bg_minivaus = @(+ bg_start 16)
bg_brick_fx = @(+ bg_start 17)
bg_brick_fx_end = @(+ bg_start 24)
