exm_round_intro:        @(fetch-file "obj-audio/round-intro.2.4000.exm")
exm_round_start:        @(fetch-file "obj-audio/round-start.2.4000.exm")
;exm_reflection_med:     @(fetch-file "obj-audio/reflection-med.1.4000.rle")
exm_game_over:          @(subseq (fetch-file "obj-audio/game-over.2.4000.exm")
                                 0 #x1e10)
