;exm_break_out:          @(fetch-file "obj/break-out.4.exm")
;exm_doh_intro:         @(fetch-file "obj/doh-intro.2.exm")
;exm_explosion:         @(fetch-file "obj/explosion.2.rle")
;exm_extension:         @(fetch-file "obj/extension.2.rle")
;exm_extra_life:         @(fetch-file "obj/extra-life.2.rle")
exm_game_over:         @(fetch-file "obj/game-over.2.exm")
;exm_laser:         @(fetch-file "obj/laser.2.rle")
;exm_lost_ball:         @(fetch-file "obj/lost-ball.2.exm")
;exm_reflection_doh:         @(fetch-file "obj/reflection-doh.2.exm")
;exm_reflection_high:         @(fetch-file "obj/reflection-high.2.rle")
;exm_reflection_low:         @(fetch-file "obj/reflection-low.2.rle")
;exm_reflection_med:         @(fetch-file "obj/reflection-med.2.rle")
exm_round_intro:         @(fetch-file "obj/round-intro.4.exm")
exm_round_start:         @(fetch-file "obj/round-start.4.exm")
exm_reflection_med:         @(fetch-file "obj/reflection-med.1.rle")
blk5_end:
